name: Qt CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        host: linux
        modules: 'qtcore qtgui'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Cache OpenCV
    - name: Cache Assimp
    - name: qmake-project
      run: qmake -project
    - name: qmake
      run: qmake
    - name: make
      run: make
