name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}'
        install-deps: 'true'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        tools-only: 'false'
        aqtversion: '==0.9.7'
        py7zrversion: '==0.10.1'
    - name: Cache OpenCV
      id: opencv-cache
      uses: actions/cache@v2
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencv-cache
    - name: Install OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:  
        dir: ./opencv-install
        cached: ${{ steps.opencv-cache.outputs.cache-hit }}
        opencv-version: '4.2.0'
        BUILD_EXAMPLES: OFF
        INSTALL_C_EXAMPLES: OFF
        INSTALL_PYTHON_EXAMPLES: OFF
        WITH_QT: OFF
    - uses: actions/checkout@v2
    - name: Create build folder
      run: mkdir -p ./build/release
    - name: qmake
      working-directory: ./build/release
      run: qmake ../../6d-pat.pro
    - name: make
      run: make -j8 --directory ./build/release
