name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    container: florianblume/6dpat-environment:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake 6dpat.pro
    - name: make
      run: make
