name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container: florianblume/6dpat:latest
    
    steps:
    - uses: actions/checkout@v2
    - name: qmake
      run: qmake 6D-PAT.pro
    - name: make
      run: make
